// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/parceiros-hero/Aurora.tsx": () => import("../components/mockups/parceiros-hero/Aurora.tsx"),
  "./components/mockups/parceiros-hero/Particles.tsx": () => import("../components/mockups/parceiros-hero/Particles.tsx"),
  "./components/mockups/parceiros-hero/Plasma.tsx": () => import("../components/mockups/parceiros-hero/Plasma.tsx"),
  "./components/mockups/parceiros-hero/Prism.tsx": () => import("../components/mockups/parceiros-hero/Prism.tsx")
};
